# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Select-ActiveAzSubscription.ps1
. $PSScriptRoot\Update-Array.ps1
. $PSScriptRoot\Delete-AzVm.ps1
. $PSScriptRoot\Find-AdObject.ps1
. $PSScriptRoot\Run-WindowsUpdate.ps1
. $PSScriptRoot\Add-LinuxUser.ps1
. $PSScriptRoot\Initialize-AzVM.ps1
. $PSScriptRoot\Suspend-AzVM.ps1
. $PSScriptRoot\Start-CyberArkSSH.ps1
. $PSScriptRoot\New-AzureOnboarding.ps1